### ISSUE TITLE
pytest fails to import `Blueprint` from `Flask`

### ISSUE THREAD

**Issue by hoytnix** [hoytnix/hoyt.io#10]
```
manjaro at alisa in ~/Websites/hoyt.io on master!
[2] $ make ci                                                                 ✘
/mnt/Jerusalem/Websites/hoyt.io/env/bin/pep257 flask/hoyt flask/tests flask/__init__.py flask/scent.py flask/setup.py
/mnt/Jerusalem/Websites/hoyt.io/env/bin/pylint flask/hoyt flask/tests flask/__init__.py flask/scent.py flask/setup.py --rcfile=flask/.pylintrc
Traceback (most recent call last):
  File "/mnt/Jerusalem/Websites/hoyt.io/env/lib/python3.5/site-packages/_pytest/config.py", line 300, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/mnt/Jerusalem/Websites/hoyt.io/flask/hoyt/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/mnt/Jerusalem/Websites/hoyt.io/env/lib/python3.5/site-packages/_pytest/config.py", line 331, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/mnt/Jerusalem/Websites/hoyt.io/flask/hoyt/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/mnt/Jerusalem/Websites/hoyt.io/env/lib/python3.5/site-packages/_pytest/config.py", line 337, in _importconftest
    mod = conftestpath.pyimport()
  File "/mnt/Jerusalem/Websites/hoyt.io/env/lib/python3.5/site-packages/py/_path/local.py", line 650, in pyimport
    __import__(modname)
  File "/mnt/Jerusalem/Websites/hoyt.io/flask/hoyt/__init__.py", line 9, in <module>
    from . import blueprints
  File "/mnt/Jerusalem/Websites/hoyt.io/flask/hoyt/blueprints/__init__.py", line 3, in <module>
    from . import blog
  File "/mnt/Jerusalem/Websites/hoyt.io/flask/hoyt/blueprints/blog/__init__.py", line 1, in <module>
    from .views import blog
  File "/mnt/Jerusalem/Websites/hoyt.io/flask/hoyt/blueprints/blog/views.py", line 1, in <module>
    from flask import Blueprint, render_template, abort
ImportError: cannot import name 'Blueprint'
ERROR: could not load /mnt/Jerusalem/Websites/hoyt.io/flask/hoyt/tests/conftest.py
```

**Comment by hoytnix** [comment]
Fixed in 03b404e226372247dd1785e25b954ef0361dd483 by renaming the `flask`-directory to `flask-server`.

The directory being named `flask` was causing a name conflict because it was considered a package in `sys.path`.
